/** Type declarations for hyrr-wasm — generated by wasm-pack build. */
declare module "hyrr-wasm" {
  export class WasmDataStore {
    constructor(library: string);
    loadElements(json: string): void;
    loadAbundances(json: string): void;
    loadDecayData(json: string): void;
    loadStoppingData(json: string): void;
    loadCrossSections(projectile: string, elementSymbol: string, json: string): void;
    computeStack(configJson: string): string;
    computeDepthPreview(configJson: string): string;
    resolveMaterial(identifier: string): string;
    static parseFormula(formula: string): string;
  }
}
