//! Impact-classified release notes for HYRR (#572).
//!
//! Machine-readable companion to `CHANGELOG.md`. The developer changelog is
//! generated by release-please from conventional commits; `release-notes.json`
//! is a human-reviewed artifact edited at release time that answers the
//! question that actually matters for a scientific tool:
//!
//! > **Would my previous answer have been wrong?**
//!
//! A commit-derived line like `fix(mcp): keep long-lived low-yield products in
//! the inventory prune` tells a developer what changed; it does NOT tell an
//! agent that the older version silently omitted isotopes. That mapping
//! (`silent: true`, `impact: physics_affecting`, `affected: [...]`) has to be
//! authored by a reviewer at release time — inventing it at runtime with an
//! LLM would be a correctness hazard, not a convenience.
//!
//! ## Wire
//!
//! - Source of truth: `release-notes.json` at the repo root.
//! - Compiled into the crate via `include_str!` — the running version's
//!   entries are always available offline (air-gapped installs behave
//!   identically). Cross-version comparison against a newer release still
//!   needs the network; that is #571's concern, not this module's.
//! - Exposed to MCP clients through the `get_changelog` tool
//!   (`core::mcp::tools`).
//!
//! ## Compile-time validation
//!
//! The parse is exercised in unit tests below (`load_returns_at_least_one_release`,
//! `parses_committed_artifact_without_panic`). We deliberately do NOT unwrap
//! at module load time — a corrupted committed artifact is a hard bug we want
//! to surface with a clear message on the first call, not a `LazyLock` panic
//! that shows up in a mid-transport diagnostic.
//!
//! ## Release-time gate
//!
//! `scripts/check-release-notes.sh` fails the release PR if the version being
//! cut is missing from this artifact — the same principle as `check-lockfiles.sh`.

use serde::{Deserialize, Serialize};

/// Raw JSON text of the committed artifact, embedded at build time.
///
/// Kept as a `pub const` so tests can round-trip the exact bytes; the parsed
/// view lives in [`load`].
pub const RELEASE_NOTES_JSON: &str = include_str!("../../release-notes.json");

/// Impact class of a single release-notes entry.
///
/// `physics_affecting` is deliberately conservative: when a reviewer is
/// unsure, they mark it affecting. A false negative tells a user their old
/// results were fine when they were not — that is the failure mode this whole
/// artifact exists to prevent.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Impact {
    /// Numerical results computed with the earlier version could differ. If
    /// paired with `silent: true`, older answers were wrong with no warning.
    PhysicsAffecting,
    /// A previous silent failure (e.g. a lookup returning zero) is now loud
    /// or fixed. May or may not have changed numerical results depending on
    /// whether callers noticed the zero.
    SilentFailureFixed,
    /// Nuclear-data bump. Results may change with zero code change — the
    /// class of drift a commit-derived changelog cannot represent.
    DataUpdate,
    /// Tool signature / behaviour visible to callers changed. Not
    /// numerically silent — a caller sees the difference.
    ApiChange,
    /// User-visible convenience, no numerical impact.
    Ux,
    /// Plumbing / CI / internal refactor. No user-visible surface changed.
    Internal,
}

impl Impact {
    /// Snake-case wire name, matching the JSON schema.
    pub fn as_str(self) -> &'static str {
        match self {
            Impact::PhysicsAffecting => "physics_affecting",
            Impact::SilentFailureFixed => "silent_failure_fixed",
            Impact::DataUpdate => "data_update",
            Impact::ApiChange => "api_change",
            Impact::Ux => "ux",
            Impact::Internal => "internal",
        }
    }
}

/// One classified change within a release.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Entry {
    /// User-facing one-liner. NOT a raw commit subject — answers
    /// "what would I compute differently now?".
    pub summary: String,
    /// Impact class (see [`Impact`]).
    pub impact: Impact,
    /// `true` = a user running the earlier version would have gotten a wrong
    /// answer with NO error, warning or log line. Load-bearing: a visible
    /// error is a stopped experiment; a silent wrong number is bad science
    /// published.
    pub silent: bool,
    /// MCP tool names whose output could differ. `["*"]` = all tools.
    pub affected: Vec<String>,
    /// Actionable one-paragraph guidance an agent can relay verbatim.
    pub guidance: String,
    /// Related GitHub issue / PR numbers.
    pub refs: Vec<u32>,
}

/// One release's classified notes.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Release {
    /// SemVer (matches the release-please tag minus the leading `v`).
    pub version: String,
    /// ISO date (`YYYY-MM-DD`) matching `CHANGELOG.md`.
    pub date: String,
    /// nucl-parquet DATA_VERSION shipped in this release (CalVer). A
    /// data-only bump can change results with zero code change — invisible
    /// in a commit-derived changelog, hence its own field.
    pub data_version: String,
    /// Classified entries for this release.
    pub entries: Vec<Entry>,
}

/// Top-level artifact shape. serde ignores unknown fields by default, which
/// keeps `$schema` / `_note` / future annotations forward-compatible. Note
/// that `Entry::impact` deliberately has NO `#[serde(default)]`: a missing
/// classification must fail to parse rather than silently become `internal`,
/// since defaulting it would be exactly the runtime inference #572 forbids.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ReleaseNotes {
    /// Releases, newest-first. Ordering is checked at release time by
    /// `scripts/check-release-notes.sh`.
    pub releases: Vec<Release>,
}

/// Parse the committed artifact. Returns a parse error on a malformed JSON
/// blob — surfaced by the MCP tool as a JSON-RPC error rather than a panic.
pub fn load() -> Result<ReleaseNotes, serde_json::Error> {
    serde_json::from_str(RELEASE_NOTES_JSON)
}

/// Compare two dotted-numeric version strings. Handles missing components
/// (`0.19` < `0.19.0`) and rejects non-numeric segments by ordering them
/// consistently — good enough for release-please tags which are always
/// `MAJOR.MINOR.PATCH`.
///
/// Kept private + tiny rather than pulling in a semver crate; the version
/// space here (single-digit major/minor, PATCH ≤ 99) is nowhere near what
/// warrants a dependency.
fn cmp_version(a: &str, b: &str) -> std::cmp::Ordering {
    let parse = |s: &str| -> Vec<u64> {
        // Strip anything after a `-` (pre-release suffix) for the numeric
        // comparison; the artifact doesn't currently use pre-releases but
        // release-please can emit them for the release PR.
        let core = s.split('-').next().unwrap_or(s);
        core.split('.')
            .map(|p| p.parse::<u64>().unwrap_or(0))
            .collect()
    };
    let av = parse(a);
    let bv = parse(b);
    let n = av.len().max(bv.len());
    for i in 0..n {
        let ai = av.get(i).copied().unwrap_or(0);
        let bi = bv.get(i).copied().unwrap_or(0);
        match ai.cmp(&bi) {
            std::cmp::Ordering::Equal => continue,
            other => return other,
        }
    }
    std::cmp::Ordering::Equal
}

impl ReleaseNotes {
    /// Releases with `version > since` (strict), newest-first. `None` returns
    /// every release (equivalent to "since the beginning of time").
    ///
    /// Load-bearing for the MCP `get_changelog` tool — shipping 645 lines of
    /// changelog into every agent's context on `initialize` is the wrong
    /// trade, so callers should almost always pass `since_version` set to
    /// what they last saw.
    pub fn since<'a>(&'a self, since: Option<&str>) -> Vec<&'a Release> {
        let Some(since) = since else {
            return self.releases.iter().collect();
        };
        self.releases
            .iter()
            .filter(|r| cmp_version(&r.version, since) == std::cmp::Ordering::Greater)
            .collect()
    }

    /// Physics-affecting entries strictly newer than `since_version`.
    ///
    /// This is the query `#571`'s handshake wants: "if you know a newer
    /// release exists AND any entry since the running version is
    /// `physics_affecting`, say so explicitly" — that is the case worth
    /// interrupting for.
    pub fn physics_affecting_since<'a>(&'a self, since: &str) -> Vec<(&'a Release, &'a Entry)> {
        let mut out = Vec::new();
        for release in self.since(Some(since)) {
            for entry in &release.entries {
                if entry.impact == Impact::PhysicsAffecting {
                    out.push((release, entry));
                }
            }
        }
        out
    }

    /// Look up a specific release by version string. `None` when the version
    /// is not in the artifact — used by the release-time gate script's Rust
    /// smoke-check counterpart and by tests.
    pub fn get(&self, version: &str) -> Option<&Release> {
        self.releases.iter().find(|r| r.version == version)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed artifact parses without error. Guards against a
    /// hand-edit that breaks the JSON before it ships.
    #[test]
    fn parses_committed_artifact_without_panic() {
        let notes = load().expect("release-notes.json must be valid JSON matching the schema");
        assert!(
            !notes.releases.is_empty(),
            "release-notes.json must contain at least one release"
        );
    }

    /// Releases are ordered newest-first — checked here so a test fails
    /// locally rather than only in the release gate script.
    #[test]
    fn releases_are_newest_first() {
        let notes = load().unwrap();
        for pair in notes.releases.windows(2) {
            let (a, b) = (&pair[0], &pair[1]);
            assert_eq!(
                cmp_version(&a.version, &b.version),
                std::cmp::Ordering::Greater,
                "releases must be newest-first: {} should be > {}",
                a.version,
                b.version
            );
        }
    }

    /// The three silent, physics-altering fixes that motivated #572 are
    /// classified correctly. This is the acceptance-test the issue calls
    /// out — if the scheme cannot classify the real bugs correctly it is
    /// not worth building.
    #[test]
    fn issue_533_488_529_are_physics_affecting_and_silent() {
        let notes = load().unwrap();
        for issue in [533u32, 488, 529] {
            let hits: Vec<&Entry> = notes
                .releases
                .iter()
                .flat_map(|r| r.entries.iter())
                .filter(|e| e.refs.contains(&issue))
                .collect();
            assert!(
                !hits.is_empty(),
                "release-notes.json must carry an entry for #{issue}"
            );
            for e in &hits {
                assert_eq!(
                    e.impact,
                    Impact::PhysicsAffecting,
                    "#{issue} must be classified `physics_affecting` (got {:?}): {}",
                    e.impact,
                    e.summary,
                );
                assert!(
                    e.silent,
                    "#{issue} must be flagged silent (users on the earlier version got no warning): {}",
                    e.summary,
                );
                assert!(
                    !e.affected.is_empty(),
                    "#{issue} must list at least one affected tool: {}",
                    e.summary,
                );
                assert!(
                    !e.guidance.trim().is_empty(),
                    "#{issue} must carry actionable guidance: {}",
                    e.summary,
                );
            }
        }
    }

    /// `since_version` filtering is strict — asking for entries "since"
    /// the newest release must return nothing, and asking without a floor
    /// must return every release.
    #[test]
    fn since_filter_is_strict_greater() {
        let notes = load().unwrap();
        let newest = notes
            .releases
            .first()
            .expect("at least one release")
            .version
            .clone();
        assert!(
            notes.since(Some(&newest)).is_empty(),
            "since(newest) must be empty — nothing is newer than newest"
        );
        assert_eq!(
            notes.since(None).len(),
            notes.releases.len(),
            "since(None) returns every release"
        );
    }

    /// `since_version` filtering across the 0.18.0 → 0.19.0 gap must
    /// return exactly the 0.19.0 entries (the release that carries the
    /// three motivating fixes).
    #[test]
    fn since_0_18_0_includes_0_19_0_entries() {
        let notes = load().unwrap();
        let hits = notes.since(Some("0.18.0"));
        assert!(
            hits.iter().any(|r| r.version == "0.19.0"),
            "since('0.18.0') must include 0.19.0"
        );
        assert!(
            hits.iter().all(|r| r.version != "0.18.0"),
            "since('0.18.0') must not include 0.18.0 itself (strict >)"
        );
    }

    /// The `physics_affecting_since` helper #571 will call at handshake
    /// time. Verifies it lifts the three motivating entries out of 0.19.0
    /// when the running version is 0.18.0.
    #[test]
    fn physics_affecting_since_0_18_0_surfaces_533_488_529() {
        let notes = load().unwrap();
        let hits = notes.physics_affecting_since("0.18.0");
        let refs: std::collections::HashSet<u32> = hits
            .iter()
            .flat_map(|(_, e)| e.refs.iter().copied())
            .collect();
        for issue in [533u32, 488, 529] {
            assert!(
                refs.contains(&issue),
                "#{issue} must show up in physics_affecting_since('0.18.0')"
            );
        }
    }

    // -- cmp_version --------------------------------------------------

    #[test]
    fn cmp_version_orders_numeric_components() {
        use std::cmp::Ordering::*;
        assert_eq!(cmp_version("0.19.0", "0.18.0"), Greater);
        assert_eq!(cmp_version("0.10.0", "0.9.0"), Greater); // NOT lexicographic
        assert_eq!(cmp_version("0.18.0", "0.18.0"), Equal);
        assert_eq!(cmp_version("0.18.1", "0.18.0"), Greater);
        assert_eq!(cmp_version("1.0.0", "0.99.99"), Greater);
    }

    #[test]
    fn cmp_version_ignores_prerelease_suffix() {
        assert_eq!(
            cmp_version("0.19.0-rc.1", "0.19.0"),
            std::cmp::Ordering::Equal,
            "release-please pre-release suffixes should compare equal to the core version",
        );
    }

    #[test]
    fn every_entry_lists_referenced_issues() {
        // A no-refs entry defeats the whole point (an agent can't cross-
        // reference silent-behaviour into concrete issues). Guard here so a
        // sloppy hand-edit fails locally rather than making the artifact
        // useless in production.
        let notes = load().unwrap();
        for r in &notes.releases {
            for e in &r.entries {
                if matches!(
                    e.impact,
                    Impact::PhysicsAffecting | Impact::SilentFailureFixed
                ) {
                    assert!(
                        !e.refs.is_empty(),
                        "physics_affecting / silent_failure_fixed entries must cite issue refs: {} ({})",
                        e.summary,
                        r.version,
                    );
                }
            }
        }
    }
}
