/**
 * Every shipped preset, driven by `#preset=<id>` (#656, epic #649).
 *
 * Replaces `presets.spec.ts`'s five hardcoded `#config=1:<base64>` URLs. Those
 * were opaque, three of them decoded to corrupt deflate streams (#559), and
 * they bake codec-version brittleness into every spec — regenerating them is
 * manual and nobody notices when they rot. `#preset=` already exists
 * (`config-url.ts:getPresetIdFromHash`) and cannot drift from the registry.
 *
 * Cases are generated by looping `PRESETS`, so a new preset is covered the
 * moment it is added rather than when someone remembers to add a spec. That
 * matters here: the four neutron presets had NO end-to-end coverage at all,
 * and "I'm feeling lucky" picks one of them 40% of the time.
 *
 * Assertions are deliberately structural — row counts, the principal isotope,
 * no unexplained empty state. Numeric physics belongs in the Rust/TS golden
 * tier (#655), not punched through DOM formatting where every UI tweak becomes
 * a spurious failure.
 */
import { test, expect, openPreset, getIsotopeCount } from "./fixtures";
import { PRESETS } from "../src/lib/presets";

/**
 * The isotope each preset is named for, e.g. "Tc-99m (Mo-100)" → Tc-99m.
 * Derived from the registry rather than hardcoded, so it cannot drift.
 */
function principalIsotope(name: string): string | null {
  const m = name.match(/^([A-Za-z]{1,2}-\d+m?)/);
  return m ? m[1] : null;
}

/** Accept both "Tc-99m" and the IUPAC "99mTc" the table may render. */
function isotopeRegex(iso: string): RegExp {
  const [sym, rest] = iso.split("-");
  const mass = rest.replace("m", "");
  const meta = rest.endsWith("m") ? "m?" : "";
  return new RegExp(`${sym}-${mass}${meta}|${mass}${meta}${sym}`, "i");
}

for (const preset of PRESETS) {
  // Every preset is @preset — there is no @preset-heavy tier any more.
  //
  // Ge-68, At-211 and Ac-225 carried that tag because they timed out at 5-13
  // minutes (#559). Driving them by `#preset=` instead of the corrupt
  // `#config=` base64 they used to carry, each completes in ~1.5 s: the app was
  // never rendering because the config never decoded, so the "slow physics" was
  // really a stalled page. Ac-225 also now produces via the clean
  // Ra-226(p,2n) route, confirming the #488 Z-named fallback end to end.
  test.describe(`preset ${preset.id}`, { tag: "@preset" }, () => {
    test(`${preset.name} computes and renders`, async ({ page, consoleViolations }) => {
      test.setTimeout(120_000);
      void consoleViolations; // fixture asserts at teardown

      await openPreset(page, preset.id);

      const rows = await getIsotopeCount(page);

      // An explained empty state is a legitimate outcome for some
      // configurations, but never for a preset we ship — a shipped preset that
      // produces nothing is exactly the reported bug.
      const emptyState = page.locator('[data-testid="diag-empty-state"]');
      if (await emptyState.count()) {
        throw new Error(
          `preset "${preset.id}" produced no isotopes. The UI explained it as: ` +
            `${(await emptyState.first().innerText()).trim()}`,
        );
      }
      expect(rows, `preset "${preset.id}" produced no rows`).toBeGreaterThan(0);

      const iso = principalIsotope(preset.name);
      if (iso) {
        const table = page.locator(".activity-table-enhanced tbody");
        await expect(table).toContainText(isotopeRegex(iso));
      }
    });
  });
}

test.describe("preset registry", { tag: "@preset" }, () => {
  test("every preset id is reachable by deep link", async ({ page, consoleViolations }) => {
    void consoleViolations;
    // Guards the generator above: if `#preset=` stopped resolving, every case
    // would fall back to an empty app and the failures would look like physics.
    await page.goto("./#preset=does-not-exist");
    await page.waitForLoadState("networkidle");
    // An unknown id must not crash the app; the fixture asserts no pageerror.
    expect(await page.locator("body").count()).toBe(1);
  });
});
