/**
 * Integration test: mock CSV → parseCurrentProfileCSV → buildTargetStack
 * Verifies the complete data path from file upload to compute pipeline input.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "fs";
import { resolve } from "path";
import { parseCurrentProfileCSV } from "../current-profile-csv";
import type { ParseResult, ParseError } from "../current-profile-csv";
import { currentProfileIntervals } from "../types";
import type { SimulationConfig } from "../config-bridge";

function isError(r: ParseResult | ParseError): r is ParseError {
  return "error" in r;
}

// Path to mock profile generated by scripts/generate_mock_current_profile.py
const MOCK_CSV_PATH = resolve(
  __dirname,
  "../../../../tests/data/mock_current_profile.csv",
);

const MOCK_VALUES_PATH = resolve(
  __dirname,
  "../../../../tests/data/mock_current_profile_values.csv",
);

describe("current profile integration", () => {
  it("parses the mock CSV and produces valid CurrentProfile", () => {
    const csv = readFileSync(MOCK_CSV_PATH, "utf-8");
    const result = parseCurrentProfileCSV(csv);

    expect(isError(result)).toBe(false);
    if (isError(result)) return;

    const { profile, warnings } = result;

    // 7200 rows at 1s intervals for 2h
    expect(profile.timesS.length).toBe(7200);
    expect(profile.currentsMA.length).toBe(7200);

    // Times start at 0 and increase
    expect(profile.timesS[0]).toBe(0);
    expect(profile.timesS[profile.timesS.length - 1]).toBe(7199);

    // Plateau around 0.05 mA
    const mid = profile.currentsMA[3600]; // midpoint
    expect(mid).toBeGreaterThan(0.03);
    expect(mid).toBeLessThan(0.06);

    // Total charge warning present
    expect(warnings.some((w) => w.includes("Total charge"))).toBe(true);
  });

  it("parses headerless values CSV with dt", () => {
    const csv = readFileSync(MOCK_VALUES_PATH, "utf-8");
    const result = parseCurrentProfileCSV(csv, 1.0);

    expect(isError(result)).toBe(false);
    if (isError(result)) return;

    expect(result.profile.timesS.length).toBe(7200);
    expect(result.profile.timesS[0]).toBe(0);
    expect(result.profile.timesS[1]).toBe(1);
  });

  it("profile intervals cover full irradiation time", () => {
    const csv = readFileSync(MOCK_CSV_PATH, "utf-8");
    const result = parseCurrentProfileCSV(csv);
    if (isError(result)) throw new Error("parse failed");

    const irradiationTime = 7200;
    const intervals = currentProfileIntervals(result.profile, irradiationTime);

    // Should have intervals
    expect(intervals.length).toBeGreaterThan(0);

    // First interval starts at 0
    expect(intervals[0][0]).toBe(0);

    // Last interval ends at irradiation time
    expect(intervals[intervals.length - 1][1]).toBe(irradiationTime);

    // All currents should be non-negative
    for (const [, , current] of intervals) {
      expect(current).toBeGreaterThanOrEqual(0);
    }
  });

  it("profile integrates into SimulationConfig", () => {
    const csv = readFileSync(MOCK_CSV_PATH, "utf-8");
    const result = parseCurrentProfileCSV(csv);
    if (isError(result)) throw new Error("parse failed");

    const config: SimulationConfig = {
      beam: { projectile: "p", energy_MeV: 16, current_mA: 0.05 },
      layers: [{ material: "Cu", thickness_cm: 0.5 }],
      irradiation_s: 7200,
      cooling_s: 86400,
      currentProfile: result.profile,
    };

    // Config should have profile
    expect(config.currentProfile).toBeDefined();
    expect(config.currentProfile!.timesS.length).toBe(7200);

    // JSON serialization for Rust backend should work
    const json = JSON.stringify(config, (_k, v) =>
      v instanceof Float64Array ? Array.from(v) : v,
    );
    const parsed = JSON.parse(json);
    expect(parsed.currentProfile.timesS.length).toBe(7200);
    expect(parsed.currentProfile.currentsMA.length).toBe(7200);
  });
});
